version: '3.9'
services:
  drl-api-service:
    build: api
    ports:
      - "8000:8000"
    restart: on-failure
    volumes:
      - ./api/app:/api/app
      - ../ray_results_deployed:/api/app/ray_results
      - ../trader:/api/app/trader
      - ../cli:/api/app/cli
      - ../dataset:/api/app/dataset
